language: ruby
sudo: false

notifications:
  email: false

rvm:
  - 2.4.2

before_install:
  - bin/setup

script:
  - bundle exec rake

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

jdk: oraclejdk8
